### ISSUE TITLE
Removes filename on node 4

### ISSUE THREAD

**Issue by vladholubiev** [electerious/rename-extension#3]
Probably because of this:

```
parsedPath.base = null
```

I have file path without file name on node 4.

Pleas add node 4 to Travis.

**Comment by electerious** [comment]
Please run `npm test` and let me know which tests are failing with node v4. You could also try to remove `parsedPath.base = null` from `rename-extension` in your `node_modules`-folder. Does this change anything?

**Comment by vladholubiev** [comment]
@electerious actually only the first test passes

```
  index()
    ✓ should throw an error when called with an invalid filePath
    1) should remove the extension when called without a newExt
    2) should remove the extension when called with an empty newExt
    3) should change the extension when called with valid parameters (absolute)
    4) should change the extension when called with valid parameters (relative)
    5) should change the extension when called with a dotfile which has an extension
    6) should add the extension when called with a dotfile which has no extension
    7) should add the extension when called with an extension-less filePath

```

**Comment by vladholubiev** [comment]
@electerious this one works best for me:

``` js
module.exports = function(filePath, newExt) {
  const parsedPath = path.parse(filePath);
  return path.join(parsedPath.dir, parsedPath.name + (newExt ? '.' + newExt : ''));
};
```

All tests pass except this one:

```
AssertionError: expected '../a/b/c.css' to equal './../a/b/c.css'
```

But in reality they are equal.

**Comment by electerious** [comment]
[6.x now has LTS](https://github.com/nodejs/LTS#lts-schedule). That's why I don't think it's necessary to adjust the code for older versions. Modifying `parsedPath.ext` to change the extension sounds like the better approach.
